--Borrar tablas
DROP TABLE CLIENTES
DROP TABLE PRODUCTOS
DROP TABLE REGISTRO_COMPRAS;
DROP TABLE STOCKPRODUCTOS;

--Creación de Tablas
CREATE TABLE Clientes (
	C_ID INTEGER PRIMARY KEY IDENTITY (1,1) NOT NULL,
	C_Email VARCHAR (50) NOT NULL,
	C_RazonSocial VARCHAR (50) NOT NULL,
	C_Password VARCHAR (50) NOT NULL,	
);

CREATE TABLE Productos (
	P_ID INTEGER PRIMARY KEY IDENTITY (1,1) NOT NULL,
	P_Nombre VARCHAR (50) NOT NULL,
	P_Precio INT NOT NULL,
	P_Cantidad INTEGER,
);

CREATE TABLE StockProductos (
	SP_ID INTEGER PRIMARY KEY IDENTITY(1,1) NOT NULL,
	P_ID INTEGER,
	CANTIDAD INTEGER,
	MONTO INTEGER,
	CONSTRAINT FKSP_ID FOREIGN KEY (P_ID) REFERENCES Productos ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE REGISTRO_COMPRAS (
	RC_ID INTEGER NOT NULL,
	C_ID INTEGER NOT NULL,
	P_ID INTEGER NOT NULL,
	MONTO INT,
	FECHA DATE,
	CONSTRAINT FKC_ID FOREIGN KEY (C_ID) REFERENCES Clientes ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FKP_ID FOREIGN KEY (P_ID) REFERENCES Productos ON UPDATE CASCADE ON DELETE CASCADE
);



--Creación de datos 
INSERT INTO Clientes VALUES (
	1, 'ClienteN#1368957@Cliente.com', 'ClienteN°1', 'ContraseñaSegura123'
);
INSERT INTO Productos VALUES (
	'Tarjeta 2800 V-Bucks', 16000, 20
);

--SELECT A LAS TABLAS PARA PRUEBAS
SELECT * FROM CLIENTES;	
SELECT * FROM PRODUCTOS;
SELECT * FROM REGISTRO_COMPRAS;
SELECT * FROM STOCKPRODUCTOS;

--VERIFICACIÓN DE IP DEL SERVIDOR
SELECT CONNECTIONPROPERTY('client_net_address') AS [IP Address]