--Borrar tablas
DROP TABLE Clientes;
DROP TABLE Productos;
DROP TABLE REGISTRO_COMPRAS;

--Creación de Tablas
CREATE TABLE Clientes (
	C_ID INTEGER PRIMARY KEY NOT NULL,
	C_Email VARCHAR (50) NOT NULL,
	C_Password VARCHAR (50) NOT NULL,	
);

CREATE TABLE REGISTRO_COMPRAS (
	RC_ID INTEGER NOT NULL,
	C_ID INTEGER NOT NULL,
	P_ID INTEGER NOT NULL,
	MONTO INT,
	FECHA DATE,
	CONSTRAINT FKC_ID FOREIGN KEY (C_ID) REFERENCES Clientes ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FKP_ID FOREIGN KEY (P_ID) REFERENCES Productos ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Productos (
	P_ID INTEGER PRIMARY KEY NOT NULL,
	P_Nombre VARCHAR (50) NOT NULL,
	P_Precio INT NOT NULL,
	P_Cantidad INT NOT NULL,
);

--Creación de datos 
INSERT INTO Clientes VALUES (
	1, 'ClienteN#1368957@Cliente.com', 'ContraseñaSegura123'
);
INSERT INTO Productos VALUES (
	1, 'Tarjeta 2800 V-Bucks', 16000, 20
);

--SELECT A LAS TABLAS PARA PRUEBAS
SELECT * FROM CLIENTES;
SELECT * FROM PRODUCTOS;

SELECT CONNECTIONPROPERTY('client_net_address') AS [IP Address]